#!/usr/bin/env python3
"""
Train the Llama 4 adapter using synthetic or real data.
This script takes the paired data generated by generate_synthetic_data.py
and trains the Llama4Adapter model to transform Llama 4 hidden states
to CSM-compatible inputs.
"""
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import pytorch_lightning as pl
from torch.utils.data import DataLoader, Dataset, random_split
from pytorch_lightning.callbacks import ModelCheckpoint, EarlyStopping, LearningRateMonitor
from pytorch_lightning.loggers import TensorBoardLogger
from argparse import ArgumentParser
from typing import Tuple, Dict, List, Optional, Any
import sys

# Add parent directory to path to import llama4_adapter
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from llama4_adapter import Llama4Adapter

class AdapterDataset(Dataset):
    """Dataset for training the Llama 4 adapter"""
    def __init__(self, data_path: str):
        print(f"Loading dataset from {data_path}")
        self.data = torch.load(data_path)
        self.llama4_states = self.data["llama4_states"]
        self.csm_inputs = self.data["csm_inputs"]
        
        # Verify shapes
        assert len(self.llama4_states) == len(self.csm_inputs), \
            f"Mismatch in dataset sizes: {len(self.llama4_states)} vs {len(self.csm_inputs)}"
        
        # Print dataset info
        print(f"Dataset loaded with {len(self.llama4_states)} samples")
        print(f"Llama 4 states shape: {self.llama4_states.shape}")
        print(f"CSM inputs shape: {self.csm_inputs.shape}")
        print(f"Data generation method: {self.data.get('method', 'unknown')}")
        
    def __len__(self) -> int:
        return len(self.llama4_states)
    
    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.llama4_states[idx], self.csm_inputs[idx]

class Llama4AdapterModule(pl.LightningModule):
    """PyTorch Lightning module for training the adapter"""
    def __init__(self, 
                 input_dim: int = 5120, 
                 output_dim: int = 4096,
                 hidden_dim: Optional[int] = None,
                 learning_rate: float = 5e-4,
                 weight_decay: float = 0.01,
                 cosine_weight: float = 0.5,
                 l1_weight: float = 0.0,
                 scheduler_type: str = "cosine",
                 warmup_steps: int = 100):
        super().__init__()
        self.save_hyperparameters()
        
        # Create adapter model
        self.model = Llama4Adapter(
            input_dim=input_dim,
            output_dim=output_dim,
            hidden_dim=hidden_dim
        )
        
        # Initialize weights
        self._init_weights()
        
    def _init_weights(self):
        """Initialize weights for better training convergence"""
        for name, p in self.model.named_parameters():
            if "weight" in name:
                nn.init.xavier_uniform_(p)
            elif "bias" in name:
                nn.init.zeros_(p)
        
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.model(x)
    
    def mse_loss(self, pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        return F.mse_loss(pred, target)
    
    def cosine_loss(self, pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        return 1.0 - F.cosine_similarity(pred, target, dim=-1).mean()
    
    def l1_regularization(self) -> torch.Tensor:
        """L1 regularization on model parameters"""
        l1_reg = torch.tensor(0.0, device=self.device)
        for param in self.model.parameters():
            l1_reg += torch.norm(param, 1)
        return l1_reg
    
    def compute_loss(self, pred: torch.Tensor, target: torch.Tensor) -> Dict[str, torch.Tensor]:
        """Compute all loss components"""
        mse = self.mse_loss(pred, target)
        cos = self.cosine_loss(pred, target)
        
        # Combined loss
        loss = (1.0 - self.hparams.cosine_weight) * mse + \
               self.hparams.cosine_weight * cos
        
        # Add L1 regularization if specified
        if self.hparams.l1_weight > 0:
            l1 = self.l1_regularization()
            loss = loss + self.hparams.l1_weight * l1
            return {"loss": loss, "mse": mse, "cos": cos, "l1": l1}
        else:
            return {"loss": loss, "mse": mse, "cos": cos}
    
    def training_step(self, batch: Tuple[torch.Tensor, torch.Tensor], batch_idx: int) -> torch.Tensor:
        x, y = batch
        y_hat = self(x)
        
        # Compute losses
        losses = self.compute_loss(y_hat, y)
        
        # Log all losses
        for name, value in losses.items():
            self.log(f"train_{name}", value, prog_bar=True if name == "loss" else False)
        
        # Also log cosine similarity (higher is better)
        cos_sim = F.cosine_similarity(y_hat, y, dim=-1).mean()
        self.log("train_cos_sim", cos_sim, prog_bar=True)
        
        return losses["loss"]
    
    def validation_step(self, batch: Tuple[torch.Tensor, torch.Tensor], batch_idx: int) -> None:
        x, y = batch
        y_hat = self(x)
        
        # Compute losses
        losses = self.compute_loss(y_hat, y)
        
        # Log all losses
        for name, value in losses.items():
            self.log(f"val_{name}", value, prog_bar=True if name == "loss" else False)
        
        # Calculate cosine similarity (higher is better)
        cos_sim = F.cosine_similarity(y_hat, y, dim=-1).mean()
        self.log("val_cos_sim", cos_sim, prog_bar=True)
    
    def configure_optimizers(self):
        optimizer = torch.optim.AdamW(
            self.parameters(),
            lr=self.hparams.learning_rate,
            weight_decay=self.hparams.weight_decay
        )
        
        # Configure learning rate scheduler
        if self.hparams.scheduler_type == "none":
            return optimizer
        
        if self.hparams.scheduler_type == "cosine":
            scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
                optimizer, 
                T_max=self.trainer.estimated_stepping_batches
            )
        elif self.hparams.scheduler_type == "linear":
            scheduler = torch.optim.lr_scheduler.LinearLR(
                optimizer,
                start_factor=1.0,
                end_factor=0.1,
                total_iters=self.trainer.estimated_stepping_batches
            )
        else:
            raise ValueError(f"Unknown scheduler type: {self.hparams.scheduler_type}")
        
        # Add warmup
        if self.hparams.warmup_steps > 0:
            warmup_scheduler = torch.optim.lr_scheduler.LinearLR(
                optimizer,
                start_factor=0.1,
                end_factor=1.0,
                total_iters=self.hparams.warmup_steps
            )
            
            scheduler = torch.optim.lr_scheduler.SequentialLR(
                optimizer,
                schedulers=[warmup_scheduler, scheduler],
                milestones=[self.hparams.warmup_steps]
            )
        
        return {
            "optimizer": optimizer,
            "lr_scheduler": {
                "scheduler": scheduler,
                "interval": "step",
                "frequency": 1
            }
        }

def main():
    parser = ArgumentParser(description="Train the Llama 4 to CSM adapter")
    
    # Data arguments
    parser.add_argument("--data_path", type=str, required=True, 
                        help="Path to the paired data file")
    parser.add_argument("--val_split", type=float, default=0.1,
                        help="Validation split ratio")
    
    # Model arguments
    parser.add_argument("--input_dim", type=int, default=5120,
                        help="Input dimension (Llama 4 hidden state size)")
    parser.add_argument("--output_dim", type=int, default=4096,
                        help="Output dimension (CSM input size)")
    parser.add_argument("--hidden_dim", type=int, default=None,
                        help="Hidden dimension (defaults to output_dim)")
    
    # Training arguments
    parser.add_argument("--batch_size", type=int, default=64,
                        help="Batch size")
    parser.add_argument("--epochs", type=int, default=20,
                        help="Number of epochs")
    parser.add_argument("--learning_rate", type=float, default=1e-3,
                        help="Learning rate")
    parser.add_argument("--weight_decay", type=float, default=0.01,
                        help="Weight decay")
    parser.add_argument("--cosine_weight", type=float, default=0.5,
                        help="Weight for cosine similarity loss (0-1)")
    parser.add_argument("--l1_weight", type=float, default=0.0,
                        help="Weight for L1 regularization")
    parser.add_argument("--scheduler_type", type=str, default="cosine",
                        choices=["none", "cosine", "linear"],
                        help="Type of learning rate scheduler")
    parser.add_argument("--warmup_steps", type=int, default=100,
                        help="Number of warmup steps for learning rate")
    
    # Early stopping
    parser.add_argument("--patience", type=int, default=5,
                        help="Patience for early stopping")
    
    # Output arguments
    parser.add_argument("--output_dir", type=str, default="checkpoints",
                        help="Output directory for checkpoints")
    parser.add_argument("--experiment_name", type=str, default="llama4_adapter",
                        help="Experiment name for logging")
    
    # Hardware arguments
    parser.add_argument("--num_workers", type=int, default=4,
                        help="Number of data loader workers")
    parser.add_argument("--precision", type=str, default="16-mixed",
                        choices=["32", "16-mixed", "bf16-mixed"],
                        help="Precision for training")
    
    args = parser.parse_args()
    
    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)
    
    # Create dataset
    dataset = AdapterDataset(args.data_path)
    
    # Split into train and validation sets
    val_size = int(len(dataset) * args.val_split)
    train_size = len(dataset) - val_size
    train_dataset, val_dataset = random_split(dataset, [train_size, val_size])
    
    print(f"Train set size: {len(train_dataset)}")
    print(f"Validation set size: {len(val_dataset)}")
    
    # Create data loaders
    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=True
    )
    
    val_loader = DataLoader(
        val_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=True
    )
    
    # Create model
    model = Llama4AdapterModule(
        input_dim=args.input_dim,
        output_dim=args.output_dim,
        hidden_dim=args.hidden_dim,
        learning_rate=args.learning_rate,
        weight_decay=args.weight_decay,
        cosine_weight=args.cosine_weight,
        l1_weight=args.l1_weight,
        scheduler_type=args.scheduler_type,
        warmup_steps=args.warmup_steps
    )
    
    # Create logger
    logger = TensorBoardLogger(
        save_dir=args.output_dir,
        name=args.experiment_name
    )
    
    # Create callbacks
    checkpoint_callback = ModelCheckpoint(
        dirpath=os.path.join(args.output_dir, args.experiment_name),
        filename="{epoch:02d}-{val_loss:.4f}-{val_cos_sim:.4f}",
        save_top_k=3,
        monitor="val_cos_sim",
        mode="max"
    )
    
    early_stop_callback = EarlyStopping(
        monitor="val_loss",
        patience=args.patience,
        mode="min"
    )
    
    lr_monitor = LearningRateMonitor(logging_interval="step")
    
    # Create trainer
    trainer = pl.Trainer(
        max_epochs=args.epochs,
        callbacks=[checkpoint_callback, early_stop_callback, lr_monitor],
        logger=logger,
        precision=args.precision,
        accelerator="auto",
        devices="auto",
    )
    
    # Print model summary
    print("\nModel Summary:")
    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Total parameters: {total_params:,}")
    print(f"Trainable parameters: {trainable_params:,}")
    
    # Train model
    print("\nStarting training...")
    trainer.fit(model, train_loader, val_loader)
    
    # Save final lightweight model (just the adapter)
    best_model_path = checkpoint_callback.best_model_path
    print(f"\nBest model saved at: {best_model_path}")
    
    # Load best model
    print("Loading best model and saving adapter-only version...")
    best_model = Llama4AdapterModule.load_from_checkpoint(best_model_path)
    
    # Save adapter-only model
    adapter_path = os.path.join(args.output_dir, f"{args.experiment_name}_adapter.pt")
    torch.save(best_model.model.state_dict(), adapter_path)
    print(f"Adapter-only model saved to: {adapter_path}")
    
    # Print final metrics
    print("\nTraining completed!")
    print(f"Best validation cosine similarity: {checkpoint_callback.best_model_score:.4f}")

if __name__ == "__main__":
    main()
